spring:
  datasource:
    url: jdbc:postgresql://dpg-d80pa8v7f7vs73d3o6o0-a.frankfurt-postgres.render.com:5432/instituto_wwnw
    username: instituto_wwnw_user
    password: CCY21x6CLdlK0YTKCArlKQOOQ8DKYRnM
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false